### ISSUE TITLE
'Ladakh' union territory is missing in India

### ISSUE THREAD

**Issue by JoyceBabu** [trickeyone/intl-subdivision#2]
The Ladakh union territory is missing under India.

https://en.wikipedia.org/wiki/States_and_union_territories_of_India#States_and_Union_territories

**Comment by trickeyone** [comment]
@JoyceBabu If you would like to submit a Pull Request with the changes, please feel free to do so. All the Subdivision information is contained in the `src/Resources/data/en.json` file. Please ensure that any territory(ies) that you add, if their names contain unicode characters, please be sure to include the unicode characters following the `\uXXXX` standard.
